services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "4000:4000"
    environment:
      DB_HOST: REEMPLAZAR
      DB_PORT: REEMPLAZAR
      DB_NAME: REEMPLAZAR
      DB_USERNAME: REEMPLAZAR
      DB_PASSWORD: REEMPLAZAR
